# Generated by Django 4.2.2 on 2023-07-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/profile_pics/default.png', upload_to='static/profile_pics'),
        ),
    ]
