# Generated by Django 4.2.2 on 2023-07-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
    ]
